### ISSUE TITLE
iHubTest插件处理系统属性时有问题

### ISSUE THREAD

**Issue by zhanghuabin** [ihub-pub/plugins#27]
### Describe the bug
添加在iHubTest/runIncludePropNames中的key，如果在启动测试时未提供该key，则该key的值被置为空串而不是null。

### To Reproduce
* 最新 **cornucopia** 的`ihub-plugin`分支
* 打开`verification_settings.gradle`第`13`行，并关闭第`12`行。
* 执行如下任务（注意：未提供`-Dtest.DupTimes`自定义参数）：

```
gradlew -Dspring.profiles.active=dev -DiHubTestClasses="**/AssetFT_08*" -Dtest.includedIDs=1010 -Dspring.config.name=service,test -Ddebug=true -DiHubTestMaxParallelForks=1 -DjacocoPackageInstructionCoverageRuleEnabled=false -DjacocoBundleBranchCoveredRatio=0.0 -DjacocoBundleInstructionCoveredRatio=0.0 cleanTest test
```

* 从异常栈中可以看到

```
For input string: ""
java.lang.NumberFormatException: For input string: ""
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Long.parseLong(Long.java:702)
	at java.base/java.lang.Long.valueOf(Long.java:1144)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.fromCache(IndyInterface.java:283)
	at com.cheche365.cheche.test.common.ALayeredTestDataFT.duplicateTestData(ALayeredTestDataFT.groovy:288)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.fromCache(IndyInterface.java:283)
	at com.cheche365.cheche.test.common.ALayeredTestDataFT.doSetupSpec(ALayeredTestDataFT.groovy:61)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.fromCache(IndyInterface.java:283)
	at com.cheche365.cheche.test.common.ASpockSpecification.setupSpec(ASpockSpecification.groovy:45)
```

* 即`test.dupTimes`不是`null`而是 **空字串** ，导致转为`long`失败

### Expected behavior
如果为提供`test.dupTimes`，那么该值应该为null。

### Additional context
执行测试任务时，需要把`.java-local,properties`暂时重命名（禁用掉），这是另一个需要改进的点，我会另外报issue。

**Comment by henry-hub** [comment]
##上述问题已经修复，但是发现还有另外一个问题，如果使用`test.includedIDs`属性，测试报告导出会有如下报错：
```
> Task :cornucopia-rest:test FAILED
Execution failed for task ':cornucopia-rest:test'.
> A build operation failed.
      Could not write XML test results for ID：#id 、DESC：#desc ，内容：#content 、文件（不显示）、预期响应：#expected 、HTTP状态码：#expectedHttpStatus ，测试addAssetPackWithForm()接口，且成功 to file D:\code\cheche\cornucopia\rest\build\test-results\test\TEST-ID#ff1a#23id#20#3001DESC#ff1a#23desc#20#ff0c#5185#5bb9#ff1a#23content#20#3001#6587#4ef6#ff08#4e0d#663e#793a#ff09#3001#9884#671f#54cd#5e94#ff1a#23expected#20#3001HTTP#72b6#6001#7801#ff1a#23expectedHttpStatus#20#ff0c#6d4b#8bd5addAssetPackWithForm#28#29#63a5#53e3#ff0c#4e14#6210#529f.xml.
   > Could not write XML test results for  #ID：#id 、DESC：#desc ，内容：#content 、文件（不显示）、预期响应：#expected 、HTTP状态码：#expectedHttpStatus ，测试addAssetPackWithForm()接口，且成功 to file D:\code\cheche\cornucopia\rest\build\test-results\test\TEST-ID#ff1a#23id#20#3001DESC#ff1a#23desc#20#ff0c#5185#5bb9#ff1a#23content#20#3001#6587#4ef6#ff08#4e0d#663e#793a#ff09#3001#9884#671f#54cd#5e94#ff1a#23expected#20#3001HTTP#72b6#6001#7801#ff1a#23expectedHttpStatus#20#ff0c#6d4b#8bd5addAssetPackWithForm#28#29#63a5#53e3#ff0c#4e14#6210#529f.xml.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```
