### ISSUE TITLE
✨ 集成 jacoco-report-aggregation 插件，便于查看各项目覆盖率合并后的报告

### ISSUE THREAD

**Issue by zhanghuabin** [ihub-pub/plugins#391]
### 问题

假设有两个项目A和B，其中B依赖于A。

A的测试用例只能用于生成A的Jacoco测试覆盖率报告，B同理。

但是B的用例通常是会跑A的代码的，所以，理应能得到A的覆盖率报告。

### 解决方案

集成`jacoco-report-aggregation`内置插件。

* 将该插件的`testCodeCoverageReport`任务提供的作为`test`任务的收尾任务之一
* 暂不考虑对各项目覆盖率合并后的验证

**Comment by zhanghuabin** [comment]
已集成，但是 **cornucopia** 项目在根项目上执行`./gradlew check ...`时，无法看到 `testCodeCoverageReport` 被执行。

所以，建议省事儿起见，把`testCodeCoverageReport`追加到`test`之后就行了，我测试过，肯定可以跑起`testCodeCoverageReport`任务。

**Comment by zhanghuabin** [comment]
`testCodeCoverageReport`任务的执行还是有点不太对劲，下面的输出是执行了`gradlew cleanTest test jacocoTestCoverageVerification testCodeCoverageReport`的结果。


<details>
<summary>出错日志</summary>
<pre><code>
> Task :cornucopia-rest:buildDashboard UP-TO-DATE
> Task :cornucopia-rest:jacocoTestCoverageVerification
> Task :testCodeCoverageReport FAILED
┌──────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                      Jacoco Report Coverage                                      │
├───────────────────────┬─────────────┬───────────┬───────────┬───────────┬───────────┬────────────┤
│ Project               │ Instruct    │ Branch    │ Line      │ Cxty      │ Method    │ Class      │
├───────────────────────┼─────────────┼───────────┼───────────┼───────────┼───────────┼────────────┤
│ cornucopia-rest       │ 76.67%      │ 60.11%    │ 78.37%    │ 60.67%    │ 79.33%    │ 88.46%     │
│ cornucopia-sdk        │ 63.80%      │ 29.41%    │ 46.00%    │ 37.04%    │ 40.54%    │ 26.67%     │
│ cornucopia-service    │ 57.45%      │ 40.45%    │ 56.12%    │ 50.17%    │ 63.13%    │ 66.29%     │
│ total                 │ 65.11%      │ 46.93%    │ 64.77%    │ 51.89%    │ 64.93%    │ 66.08%     │
└───────────────────────┴─────────────┴───────────┴───────────┴───────────┴───────────┴────────────┘
FAILURE: Build failed with an exception.
* What went wrong:
Could not resolve all files for configuration ':aggregateCodeCoverageReportResults'.
> Could not find com.cheche365.common2:common-signature:.
  Required by:
      project : > project :cornucopia-rest
> Could not find com.alibaba:druid-spring-boot-starter:.
  Required by:
      project : > project :cornucopia-rest
> Could not find com.cheche365.common:cheche365-common-core:.
  Required by:
      project : > project :cornucopia-service
> Could not find com.cheche365.common:cheche365-common-business:.
  Required by:
      project : > project :cornucopia-service
> Could not find com.huaweicloud:esdk-obs-java:.
  Required by:
      project : > project :cornucopia-service
> Could not find de.flapdoodle.embed:de.flapdoodle.embed.mongo.spring30x:.
  Required by:
      project : > project :cornucopia-test
* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
* Exception is:
org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':aggregateCodeCoverageReportResults'.
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.mapFailure(DefaultConfiguration.java:1595)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$3900(DefaultConfiguration.java:166)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$DefaultResolutionHost.mapFailure(DefaultConfiguration.java:2278)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$DefaultResolutionHost.rethrowFailure(DefaultConfiguration.java:2283)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.visitContents(DefaultConfiguration.java:1563)
	at org.gradle.api.internal.file.AbstractFileCollection.visitStructure(AbstractFileCollection.java:366)
	at org.gradle.api.internal.file.CompositeFileCollection.lambda$visitContents$0(CompositeFileCollection.java:124)
	at org.gradle.api.internal.file.collections.UnpackingVisitor.add(UnpackingVisitor.java:67)
	at org.gradle.api.internal.file.collections.UnpackingVisitor.add(UnpackingVisitor.java:92)
	at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection$UnresolvedItemsCollector.visitContents(DefaultConfigurableFileCollection.java:370)
	at org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection.visitChildren(DefaultConfigurableFileCollection.java:279)
	at org.gradle.api.internal.file.CompositeFileCollection.visitContents(CompositeFileCollection.java:124)
	at org.gradle.api.internal.file.AbstractFileCollection.getFiles(AbstractFileCollection.java:130)
	at org.gradle.api.internal.file.AbstractFileCollection.iterator(AbstractFileCollection.java:171)
	at com.google.common.collect.Iterables.any(Iterables.java:634)
	at org.gradle.testing.jacoco.tasks.JacocoReportBase$1.isSatisfiedBy(JacocoReportBase.java:65)
	at org.gradle.testing.jacoco.tasks.JacocoReportBase$1.isSatisfiedBy(JacocoReportBase.java:62)
	at org.gradle.api.internal.tasks.execution.SelfDescribingSpec.isSatisfiedBy(SelfDescribingSpec.java:40)
	at org.gradle.api.specs.AndSpec.findUnsatisfiedSpec(AndSpec.java:67)
	at org.gradle.api.internal.tasks.execution.DescribingAndSpec.findUnsatisfiedSpec(DescribingAndSpec.java:58)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:50)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:42)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:338)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:325)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:318)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:304)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:463)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:380)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
Cause 1: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.cheche365.common2:common-signature:.
Required by:
    project : > project :cornucopia-rest
Cause 2: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.alibaba:druid-spring-boot-starter:.
Required by:
    project : > project :cornucopia-rest
Cause 3: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.cheche365.common:cheche365-common-core:.
Required by:
    project : > project :cornucopia-service
Cause 4: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.cheche365.common:cheche365-common-business:.
Required by:
    project : > project :cornucopia-service
Cause 5: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.huaweicloud:esdk-obs-java:.
Required by:
    project : > project :cornucopia-service
Cause 6: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find de.flapdoodle.embed:de.flapdoodle.embed.mongo.spring30x:.
Required by:
    project : > project :cornucopia-test
* Get more help at https://help.gradle.org
BUILD FAILED in 18s
33 actionable tasks: 13 executed, 20 up-to-date
</code></pre>
</details>

**Comment by henry-hub** [comment]
1. 根项目不是Java项目时，自己本身是没有`test`任务的，因此配置的`testCodeCoverageReport`和`testAggregateTestReport`是不生效的，记得之前应该是试过用`test`任务依赖，会报错根项目不存在`test`任务，后来才绑定的`check`任务
2. 后续的话`check`任务也将不在依赖两个聚合任务，聚合报告是用来查看的，`check`任务往往用于一些后台检查，比如CI/CO检查，集合报告没有什么意义
3. iHub插件只做聚合插件配置，如果需要查看聚合报告，执行`testCodeCoverageReport`和`testAggregateTestReport`命令即可

**Comment by zhanghuabin** [comment]
确实，后续 **Report** 类型的任务就由Gradle使用者自行添加即可。
